include $(THEOS)/makefiles/common.mk

BUNDLE_NAME := MusorDropTrollTweakPrefs
MusorDropTrollTweakPrefs_FILES := MDRootListController.m
MusorDropTrollTweakPrefs_INSTALL_PATH := /Library/PreferenceBundles
MusorDropTrollTweakPrefs_FRAMEWORKS := UIKit
MusorDropTrollTweakPrefs_CFLAGS := -fobjc-arc
MusorDropTrollTweakPrefs_LDFLAGS := -Wl,-undefined,dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
